server:
  port: 8080
elasticsearch:
  host: elasticsearch.gmall
spring:
  application:
    name: gmall-search
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gmall:8848
  redis:
    host: redis.gmall
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis

#logging:
#  level:
#    com.atguigu.gmall.search: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

